Remove deprecated files and refactor project structure. Deleted file.md and unraid_api_client.py, updated README.md and PUBLISHING.md to reflect changes in package naming and usage. Adjusted requirements.txt and GitHub Actions workflows for improved functionality and clarity.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,10 +32,10 @@ jobs:
     - name: Run tests
       run: |
         cd $(find . -name "setup.py" | xargs dirname)
-        pytest --cov=pyunraid || true  # Adding || true to continue even if tests fail for now
+        pytest --cov=unraid_api || true  # Adding || true to continue even if tests fail for now
     - name: Check code formatting
       run: |
         cd $(find . -name "setup.py" | xargs dirname)
         pip install black isort
-        black --check pyunraid || true
-        isort --check pyunraid || true 
+        black --check unraid_api || true
+        isort --check unraid_api || true 
